# Playbook that configures interface parameters.

---

  - hosts: eos
    gather_facts: no

    tasks:

      - name: Backup eos device
        eos_config:
          backup: yes
        register: "{{ inventory_hostname }}"

      - name: Setup eos interfaces
        eos_interface:
          name: "{{ item['name'] }}"
          enabled: "{{ item['enabled'] }}"
          state: "{{ item['state'] }}"
        loop: "{{ interfaces }}"
    
      - name: Set no switchport eos
        eos_config:
          lines: no switchport
          parents: interface {{ item['name'] }}
        loop: "{{ interfaces }}"
        when: 
              - item['switchport'] is defined
              - item['switchport'] == False

      - name: Setup layer3 eos
        eos_l3_interface:
          name: "{{ item['name'] }}"
          ipv4: "{{ item['ipv4'] }}"
        loop: "{{ interfaces }}"

      - name: Save eos configuration
        eos_config:
          save_when: modified      

  - hosts: nxos
    gather_facts: no

    tasks:

      - name: Backup nxos device
        nxos_config:
          backup: yes
        register: "{{ inventory_hostname }}"

      - name: Setup nxos interfaces
        nxos_interface:
          name: "{{ item['name'] }}"
          admin_state: "{{ item['admin_state'] }}"
          mode: "{{ item['mode'] }}"
        loop: "{{ interfaces }}"

      - name: Setup layer3 nxos
        nxos_l3_interface:  
          name: "{{ item['name'] }}"
          ipv4: "{{ item['ipv4'] }}"
        loop: "{{ interfaces }}"
      
      - name: Save nxos configuration
        nxos_config:
          save_when: modified
        changed_when: false